START {
    NEW-TYPE: Vec<NEW-TYPE>,
}

ENUMERATION-ALTERNATIVE-NAME {
    ENUMERATION-ALTERNATIVE-NAME: String,
}

ENUMERATION {
    ENUMERATION-ALTERNATIVE-NAME: Vec<ENUMERATION-ALTERNATIVE-NAME>,
}

NEW-TYPE {
    TYPE-NAME: TYPE-NAME,
    TYPE-DEFINITION: TYPE-DEFINITION,
}

STRUCTURE-FIELD-NAME {
    STRUCTURE-FIELD-NAME: String,
}

STRUCTURE {
    STRUCTURE-FIELD-NAME: Vec<STRUCTURE-FIELD-NAME>
}

TYPE-DEFINITION: STRUCTURE | ENUMERATION

TYPE-NAME {
    TYPE-NAME: String,
}
